#!/bin/sh -e
######################################################################
#
# pml
#
######################################################################

PROJECT=pml-2.03
. ./config.cfg


######################################################################

cd ..
echo "$me: Copying source to $PROJECT ..."
cp -R -- $SOURCES/* $PROJECT/
echo "$me: Chmod source in $PROJECT ..."
chmod -R u+w $PROJECT

echo "$me: Patching source files ..."
cd $PROJECT/pmlsrc

# SYSROOTUSR is in fact just the install path which can be the
# actual SYSROOTUSR if building --with-sysroot or PREFIX
# otherwise.
SYSROOTUSR="${PREFIX}"

CPPFLAGS="-DIEEE -DNO_DBUG -I."
CFLAGS="$CPPFLAGS -O2 -fomit-frame-pointer -B$SYSROOTUSR"

CFLAGS16="-mshort $CFLAGS \$(CPUFLAGS)"
CFLAGS32="-mnoshort $CFLAGS \$(CPUFLAGS)"

sed -i Makefile    -e "s:^\(WITH_SHORT_LIBS =\).*:\1 1:g"
sed -i Makefile.16 -e "s:^\(CFLAGS =\).*:\1 ${CFLAGS16}:g"
sed -i Makefile.32 -e "s:^\(CFLAGS =\).*:\1 ${CFLAGS32}:g"
sed -i Makefile Makefile.16 Makefile.32 -e "
s:^\(CROSSDIR =\).*:\1 \\\$(DESTDIR)$SYSROOTUSR:g
s:^\(CROSSLIB =\).*:\1 \\\$(CROSSDIR)\\\$(LIBDIR):g
s:^\(CC =\).*:\1 $STAGE1/bin/m68k-atari-mint-gcc:g
s:^\(AR =\).*:\1 $STAGE1/bin/m68k-atari-mint-ar:g
"

cd ..
cp -R -- pmlsrc pmlsrc-m68000
cp -R -- pmlsrc pmlsrc-m68020
mv    -- pmlsrc pmlsrc-mcfv4e

cat >Makefile <<EOF
# Auto generated by $(basename $0)
#

export DESTDIR

all: all-m68000 all-m68020 all-mcfv4e

clean: clean-m68000 clean-m68020 clean-mcfv4e
clean-%:
	make -C pmlsrc-\$* clean

install: install-m68000 install-m68020 install-mcfv4e
install-m68000: MATHLIB=lib
install-m68020: MATHLIB=lib/m68020-60
install-mcfv4e: MATHLIB=lib/m5475
install-%:
	make -C pmlsrc-\$* install LIBDIR=/\$(MATHLIB) SYSROOT=''

all-m68000: CPU=-m68000
all-m68020: CPU=-m68020-60
all-mcfv4e: CPU=-mcfv4e

all-%:
	make -C pmlsrc-\$* CPUFLAGS=\$(CPU) all

#.PHONY: all-m68000 all-m68020 all-mcfv4e clean-m68000 clean-m68020 clean-mcfv4e
EOF

######################################################################
 

######################################################################

echo "> make -C $PROJECT"
